class ErrorTypes:
    BAD_INDEX_TYPE = 0
    BAD_INITIALIZATION = 1
    BAD_STORAGE = 2
    BAD_OPERATION = 3
    EMPTY = 4
    INVALID_ARGUMENT = 5
    INVALID_ADVERB_ARGUMENT = 6
    OUT_OF_BOUNDS = 7
    SHAPE_MISMATCH = 8
    TEST_ERROR = 9
    UNSUPPORTED_OBJECT = 10
    UNSUPPORTED_SUBJECT = 11
    UNKNOWN_KEY = 12
    UNEQUAL_ARRAY_LENGTHS = 13
    DIVISION_BY_ZERO = 14
